In [2]:
import numpy as np
import pandas as pd

In [20]:
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["Row1", "Row2","Row3","Row4","Row5"],columns=["Column1", "Column2","Column3","Column4"])
df

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [26]:
df1 = pd.DataFrame(data=np.arange(0, 16).reshape(4,4), index = ['Store_A','Store_B','Store_C','Store_D'], columns=['Product','Units_Sold','Unit_Price','Total_Sales'])

In [27]:
df1

         Product  Units_Sold  Unit_Price  Total_Sales
Store_A        0           1           2            3
Store_B        4           5           6            7
Store_C        8           9          10           11
Store_D       12          13          14           15

In [30]:
import numpy as np
import pandas as pd
data = {
    'product': ['Laptop','Mobile','Tablet','Headphones','Monitor'],
    'Units_Sold': [150,300,120,250,100],
    'Unit_Price': [50000,15000,20000,3000, 12000],
    'Total_Sales': [7500000,4500000,2400000,None,1200000],
    'Region': ['North','South','East','West','North']
}

In [31]:

df = pd.DataFrame(data, index=['Store1','Store2','Store3','Store4','Store5',])

In [32]:
df

           product  Units_Sold  Unit_Price  Total_Sales Region
Store1      Laptop         150       50000    7500000.0  North
Store2      Mobile         300       15000    4500000.0  South
Store3      Tablet         120       20000    2400000.0   East
Store4  Headphones         250        3000          NaN   West
Store5     Monitor         100       12000    1200000.0  North

In [33]:
df.loc['Store1']

product           Laptop
Units_Sold           150
Unit_Price         50000
Total_Sales    7500000.0
Region             North
Name: Store1, dtype: object

In [34]:
df.iloc[:2, 2:]

        Unit_Price  Total_Sales Region
Store1       50000    7500000.0  North
Store2       15000    4500000.0  South

In [35]:
df.isnull()

        product  Units_Sold  Unit_Price  Total_Sales  Region
Store1    False       False       False        False   False
Store2    False       False       False        False   False
Store3    False       False       False        False   False
Store4    False       False       False         True   False
Store5    False       False       False        False   False

In [36]:
df.isnull().sum()

product        0
Units_Sold     0
Unit_Price     0
Total_Sales    1
Region         0
dtype: int64

In [39]:
df['Total_Sales'].value_counts()

Total_Sales
7500000.0    1
4500000.0    1
2400000.0    1
1200000.0    1
Name: count, dtype: int64

In [41]:
df['product'].unique()

array(['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Monitor'],
      dtype=object)

In [44]:
data1 = {
    'product': ['Laptop','Laptop','Tablet','Tablet','Monitor']
}

In [49]:
df1 = pd.DataFrame(data1)

In [50]:
df1['product'].unique()

array(['Laptop', 'Tablet', 'Monitor'], dtype=object)