In [4]:
import pandas as pd

In [5]:
df = pd.Series([1,2,3,4,5,6], index=['a','b','c','d','e','f'])

In [6]:
df

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [7]:
df = pd.DataFrame({'names': ['Chinmay','Rohan','splash'], "marks": [70,53,20], 'Age': [18,60,30]})

In [8]:
df.ndim

2

In [9]:
df

     names  marks  Age
0  Chinmay     70   18
1    Rohan     53   60
2   splash     20   30

In [10]:
df = pd.read_csv('Iris.csv')

In [12]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
type(df[['Id','SepalLengthCm']])

pandas.core.frame.DataFrame

In [21]:
df[['Id','SepalLengthCm']]

      Id  SepalLengthCm
0      1            5.1
1      2            4.9
2      3            4.7
3      4            4.6
4      5            5.0
..   ...            ...
145  146            6.7
146  147            6.3
147  148            6.5
148  149            6.2
149  150            5.9

[150 rows x 2 columns]

In [22]:
df.iloc[0]

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [33]:
df2 = pd.read_csv('data.csv')

In [34]:
df2.head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  1.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            NaN           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           NaN            1.3           0.2          NaN
3  4.0            4.6           3.1            1.5           NaN  Iris-setosa
4  NaN            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df2.dropna() #removing row: missing data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
5,6.0,5.4,3.9,1.7,0.4,Iris-setosa
6,7.0,4.6,3.4,1.4,0.3,Iris-setosa
7,8.0,5.0,3.4,1.5,0.2,Iris-setosa
8,9.0,4.4,2.9,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

In [37]:
df2.fillna(0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
1,2.0,0.0,3.0,1.4,0.2,Iris-setosa
2,3.0,4.7,0.0,1.3,0.2,0
3,4.0,4.6,3.1,1.5,0.0,Iris-setosa
4,0.0,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

In [38]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [41]:
df.rename(columns={"SepalLengthCm": "SL"})

      Id   SL  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1  5.1           3.5            1.4           0.2     Iris-setosa
1      2  4.9           3.0            1.4           0.2     Iris-setosa
2      3  4.7           3.2            1.3           0.2     Iris-setosa
3      4  4.6           3.1            1.5           0.2     Iris-setosa
4      5  5.0           3.6            1.4           0.2     Iris-setosa
..   ...  ...           ...            ...           ...             ...
145  146  6.7           3.0            5.2           2.3  Iris-virginica
146  147  6.3           2.5            5.0           1.9  Iris-virginica
147  148  6.5           3.0            5.2           2.0  Iris-virginica
148  149  6.2           3.4            5.4           2.3  Iris-virginica
149  150  5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 6 columns]

In [43]:
import numpy as np

In [47]:
f = np.arange(0,5)

In [57]:
h = pd.DataFrame(index=['r1','r2','r3','r4'], columns=['c1','c2','c3','c4'])

In [ ]:
h.rename(columns={'c1': 'cg'})

     cg   c2   c3   c4
r1  NaN  NaN  NaN  NaN
r2  NaN  NaN  NaN  NaN
r3  NaN  NaN  NaN  NaN
r4  NaN  NaN  NaN  NaN

In [73]:
df.rename(columns={"SepalLengthCm": "SL"})

      Id   SL  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1  5.1           3.5            1.4           0.2     Iris-setosa
1      2  4.9           3.0            1.4           0.2     Iris-setosa
2      3  4.7           3.2            1.3           0.2     Iris-setosa
3      4  4.6           3.1            1.5           0.2     Iris-setosa
4      5  5.0           3.6            1.4           0.2     Iris-setosa
..   ...  ...           ...            ...           ...             ...
145  146  6.7           3.0            5.2           2.3  Iris-virginica
146  147  6.3           2.5            5.0           1.9  Iris-virginica
147  148  6.5           3.0            5.2           2.0  Iris-virginica
148  149  6.2           3.4            5.4           2.3  Iris-virginica
149  150  5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 6 columns]

In [74]:
df.head()

   Id   SL  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1  5.1           3.5            1.4           0.2  Iris-setosa
1   2  4.9           3.0            1.4           0.2  Iris-setosa
2   3  4.7           3.2            1.3           0.2  Iris-setosa
3   4  4.6           3.1            1.5           0.2  Iris-setosa
4   5  5.0           3.6            1.4           0.2  Iris-setosa

In [112]:
df.describe()

               Id          SL  SepalWidthCm  PetalWidthCm  zeros
count  150.000000  150.000000    150.000000    150.000000  150.0
mean    75.500000    5.386667      2.646667      1.198667    1.0
std     43.445368    0.841752      0.532648      0.763161    0.0
min      1.000000    4.000000      2.000000      0.100000    1.0
25%     38.250000    5.000000      2.000000      0.300000    1.0
50%     75.500000    5.000000      3.000000      1.300000    1.0
75%    112.750000    6.000000      3.000000      1.800000    1.0
max    150.000000    7.000000      4.000000      2.500000    1.0

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    int64
 2   SepalWidthCm   150 non-null    int64
 3   PetalLengthCm  150 non-null    string
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
 6   zeros          150 non-null    int64
 7   zeros + 1      0 non-null      object
dtypes: float64(1), int64(4), object(2), string(1)
memory usage: 9.5+ KB

In [114]:
df['SL'] = df['SL'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    int64
 2   SepalWidthCm   150 non-null    int64
 3   PetalLengthCm  150 non-null    string
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
 6   zeros          150 non-null    int64
 7   zeros + 1      0 non-null      object
dtypes: float64(1), int64(4), object(2), string(1)
memory usage: 9.5+ KB

In [115]:
# df['Id'].astype(str).info()
df['SepalWidthCm'] = df['SepalWidthCm'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    int64
 2   SepalWidthCm   150 non-null    int64
 3   PetalLengthCm  150 non-null    string
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
 6   zeros          150 non-null    int64
 7   zeros + 1      0 non-null      object
dtypes: float64(1), int64(4), object(2), string(1)
memory usage: 9.5+ KB

In [119]:
# df['PetalLengthCm'] = df['PetalLengthCm'].astype(str)
# df['PetalLengthCm'] = df['PetalLengthCm'].astype("int")
df['PetalLengthCm'] = df['PetalLengthCm'].astype(float).astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    int64
 2   SepalWidthCm   150 non-null    int64
 3   PetalLengthCm  150 non-null    int64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
 6   zeros          150 non-null    int64
 7   zeros + 1      0 non-null      object
dtypes: float64(1), int64(5), object(2)
memory usage: 9.5+ KB

In [120]:
df["zeros"] = [0 for i in range(len(df))]

In [121]:
df

,Id,SL,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,zeros,zeros + 1
0,1,5,3,1,0.2,Iris-setosa,0,None
1,2,4,3,1,0.2,Iris-setosa,0,None
2,3,4,3,1,0.2,Iris-setosa,0,None
3,4,4,3,1,0.2,Iris-setosa,0,None
4,5,5,3,1,0.2,Iris-setosa,0,None
...,...,...,...,...,...,...,...,...
145,146,6,3,5,2.3,Iris-virginica,0,None
146,147,6,2,5,1.9,Iris-virginica,0,None
147,148,6,3,5,2.0,Iris-virginica,0,None
148,149,6,3,5,2.3,Iris-virginica,0,None
149,150,5,3,5,1.8,Iris-virginica,0,None

In [123]:
def fx(a):
    a * a

df["zeros + 1"] = df["PetalLengthCm"].apply(fx)

In [124]:
df

,Id,SL,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,zeros,zeros + 1
0,1,5,3,1,0.2,Iris-setosa,0,None
1,2,4,3,1,0.2,Iris-setosa,0,None
2,3,4,3,1,0.2,Iris-setosa,0,None
3,4,4,3,1,0.2,Iris-setosa,0,None
4,5,5,3,1,0.2,Iris-setosa,0,None
...,...,...,...,...,...,...,...,...
145,146,6,3,5,2.3,Iris-virginica,0,None
146,147,6,2,5,1.9,Iris-virginica,0,None
147,148,6,3,5,2.0,Iris-virginica,0,None
148,149,6,3,5,2.3,Iris-virginica,0,None
149,150,5,3,5,1.8,Iris-virginica,0,None

In [126]:
df.to_csv('newData.csv', index=False)

## merging

In [127]:
df1 = pd.DataFrame({
    "Name": ['Rohan','Sohan','kokila','sonam','megha'],
    "Marks": [98,64,88,22,7]
})

In [128]:
df2 = pd.DataFrame({
    "Name": ['Ranu','kushi','sahu','aprva','nuha'],
    "Marks": [24,35,45,77,74]
})

In [134]:
pd.concat([df1, df2])

     Name  Marks
0   Rohan     98
1   Sohan     64
2  kokila     88
3   sonam     22
4   megha      7
0    Ranu     24
1   kushi     35
2    sahu     45
3   aprva     77
4    nuha     74

In [161]:
df1 = pd.DataFrame({
     "Name": ['Ranu','kushi'],
     "Marks": [24,35]
})

In [162]:
df2 = pd.DataFrame({
     "Name": ['megha','sonam'],
     "roll": [1224,1225]
})

In [163]:
pd.merge(df1, df2, on="Name")

Empty DataFrame
Columns: [Name, Marks, roll]
Index: []