In [4]:
import pandas as pd

In [5]:
df = pd.Series([1,2,3,4,5,6], index=['a','b','c','d','e','f'])

In [6]:
df

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [7]:
df = pd.DataFrame({'names': ['Chinmay','Rohan','splash'], "marks": [70,53,20], 'Age': [18,60,30]})

In [8]:
df.ndim

2

In [9]:
df

     names  marks  Age
0  Chinmay     70   18
1    Rohan     53   60
2   splash     20   30

In [10]:
df = pd.read_csv('Iris.csv')

In [12]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
type(df[['Id','SepalLengthCm']])

pandas.core.frame.DataFrame

In [21]:
df[['Id','SepalLengthCm']]

      Id  SepalLengthCm
0      1            5.1
1      2            4.9
2      3            4.7
3      4            4.6
4      5            5.0
..   ...            ...
145  146            6.7
146  147            6.3
147  148            6.5
148  149            6.2
149  150            5.9

[150 rows x 2 columns]

In [22]:
df.iloc[0]

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [33]:
df2 = pd.read_csv('data.csv')

In [34]:
df2.head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  1.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            NaN           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           NaN            1.3           0.2          NaN
3  4.0            4.6           3.1            1.5           NaN  Iris-setosa
4  NaN            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df2.dropna() #removing row: missing data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
5,6.0,5.4,3.9,1.7,0.4,Iris-setosa
6,7.0,4.6,3.4,1.4,0.3,Iris-setosa
7,8.0,5.0,3.4,1.5,0.2,Iris-setosa
8,9.0,4.4,2.9,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

In [37]:
df2.fillna(0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
1,2.0,0.0,3.0,1.4,0.2,Iris-setosa
2,3.0,4.7,0.0,1.3,0.2,0
3,4.0,4.6,3.1,1.5,0.0,Iris-setosa
4,0.0,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

In [38]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [41]:
df.rename(columns={"SepalLengthCm": "SL"})

      Id   SL  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1  5.1           3.5            1.4           0.2     Iris-setosa
1      2  4.9           3.0            1.4           0.2     Iris-setosa
2      3  4.7           3.2            1.3           0.2     Iris-setosa
3      4  4.6           3.1            1.5           0.2     Iris-setosa
4      5  5.0           3.6            1.4           0.2     Iris-setosa
..   ...  ...           ...            ...           ...             ...
145  146  6.7           3.0            5.2           2.3  Iris-virginica
146  147  6.3           2.5            5.0           1.9  Iris-virginica
147  148  6.5           3.0            5.2           2.0  Iris-virginica
148  149  6.2           3.4            5.4           2.3  Iris-virginica
149  150  5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 6 columns]

In [43]:
import numpy as np

In [47]:
f = np.arange(0,5)

In [57]:
h = pd.DataFrame(index=['r1','r2','r3','r4'], columns=['c1','c2','c3','c4'])

In [ ]:
h.rename(columns={'c1': 'cg'})

     cg   c2   c3   c4
r1  NaN  NaN  NaN  NaN
r2  NaN  NaN  NaN  NaN
r3  NaN  NaN  NaN  NaN
r4  NaN  NaN  NaN  NaN

In [73]:
df.rename(columns={"SepalLengthCm": "SL"})

      Id   SL  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1  5.1           3.5            1.4           0.2     Iris-setosa
1      2  4.9           3.0            1.4           0.2     Iris-setosa
2      3  4.7           3.2            1.3           0.2     Iris-setosa
3      4  4.6           3.1            1.5           0.2     Iris-setosa
4      5  5.0           3.6            1.4           0.2     Iris-setosa
..   ...  ...           ...            ...           ...             ...
145  146  6.7           3.0            5.2           2.3  Iris-virginica
146  147  6.3           2.5            5.0           1.9  Iris-virginica
147  148  6.5           3.0            5.2           2.0  Iris-virginica
148  149  6.2           3.4            5.4           2.3  Iris-virginica
149  150  5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 6 columns]

In [74]:
df.head()

   Id   SL  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1  5.1           3.5            1.4           0.2  Iris-setosa
1   2  4.9           3.0            1.4           0.2  Iris-setosa
2   3  4.7           3.2            1.3           0.2  Iris-setosa
3   4  4.6           3.1            1.5           0.2  Iris-setosa
4   5  5.0           3.6            1.4           0.2  Iris-setosa

In [75]:
df.describe()

               Id          SL  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000  150.000000    150.000000     150.000000    150.000000
mean    75.500000    5.843333      3.054000       3.758667      1.198667
std     43.445368    0.828066      0.433594       1.764420      0.763161
min      1.000000    4.300000      2.000000       1.000000      0.100000
25%     38.250000    5.100000      2.800000       1.600000      0.300000
50%     75.500000    5.800000      3.000000       4.350000      1.300000
75%    112.750000    6.400000      3.300000       5.100000      1.800000
max    150.000000    7.900000      4.400000       6.900000      2.500000

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [80]:
df['SL'] = df['SL'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    int64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(3), int64(2), object(1)
memory usage: 7.2+ KB

In [89]:
# df['Id'].astype(str).info()
df['SepalWidthCm'] = df['SepalWidthCm'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    int64
 2   SepalWidthCm   150 non-null    int64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(2), int64(3), object(1)
memory usage: 7.2+ KB

In [91]:
df['PetalLengthCm'] = df['PetalLengthCm'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SL             150 non-null    int64
 2   SepalWidthCm   150 non-null    int64
 3   PetalLengthCm  150 non-null    object
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 7.2+ KB