In [1]:
import pandas as pd

In [7]:
data = [10,20,30,40,50]

df = pd.Series(data)
df

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
data = {
    'Name': ['Chinmay','Aditya'],
    'Age': ['18','20']

}

df = pd.DataFrame(data)
df

      Name Age
0  Chinmay  18
1   Aditya  20

In [14]:
df.head(1)

      Name Age
0  Chinmay  18

In [13]:
df.tail(1)

     Name Age
1  Aditya  20

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      object
dtypes: object(2)
memory usage: 164.0+ bytes

In [16]:
df.shape

(2, 2)

In [55]:
df.columns

Index(['Name', 'Age', 'Branch', 'City'], dtype='object')

In [69]:
data = {
    'Name': ['Chinmay','Kashish','Aditya','Jyoti'],
    'Age': [18, 20, 20, 18],
    'Branch': ['AI&DS-A','AI&DS-B','AI&DS-A','AI&DS-B']

}

df = pd.DataFrame(data)
df

      Name  Age   Branch
0  Chinmay   18  AI&DS-A
1  Kashish   20  AI&DS-B
2   Aditya   20  AI&DS-A
3    Jyoti   18  AI&DS-B

In [70]:
df.describe()

             Age
count   4.000000
mean   19.000000
std     1.154701
min    18.000000
25%    18.000000
50%    19.000000
75%    20.000000
max    20.000000

In [71]:
df.shape

(4, 3)

In [72]:
df[['Name','Age','Branch']]

      Name  Age   Branch
0  Chinmay   18  AI&DS-A
1  Kashish   20  AI&DS-B
2   Aditya   20  AI&DS-A
3    Jyoti   18  AI&DS-B

In [73]:
#particular information
df.loc[0]
df.loc[1]

Name      Kashish
Age            20
Branch    AI&DS-B
Name: 1, dtype: object

In [74]:
df.iloc[0]

Name      Chinmay
Age            18
Branch    AI&DS-A
Name: 0, dtype: object

In [75]:
df[df['Age'] > 17]

      Name  Age   Branch
0  Chinmay   18  AI&DS-A
1  Kashish   20  AI&DS-B
2   Aditya   20  AI&DS-A
3    Jyoti   18  AI&DS-B

In [76]:
df['City'] = ['Dungarpur','Junjunu','GangaNagar','Japan']

In [77]:
df

      Name  Age   Branch        City
0  Chinmay   18  AI&DS-A   Dungarpur
1  Kashish   20  AI&DS-B     Junjunu
2   Aditya   20  AI&DS-A  GangaNagar
3    Jyoti   18  AI&DS-B       Japan

In [88]:
df.at[3, 'Age'] = 28

In [89]:
df

      Name  Age   Branch        City
0  Chinmay   18  AI&DS-A   Dungarpur
1  Kashish   20  AI&DS-B     Junjunu
2   Aditya   20  AI&DS-A  GangaNagar
3    Jyoti   28  AI&DS-B       Japan

In [90]:
pd.Series([1,2,3,4,5,6])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [91]:
df = pd.read_csv('prices.csv')

In [95]:
df.head()
# df.describe()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [100]:
df[['Year','Variable_code']]

       Year Variable_code
0      2024           H01
1      2024           H04
2      2024           H05
3      2024           H07
4      2024           H08
...     ...           ...
55615  2013           H37
55616  2013           H38
55617  2013           H39
55618  2013           H40
55619  2013           H41

[55620 rows x 2 columns]

In [104]:
df.iloc[0]

Year                                                                        2024
Industry_aggregation_NZSIOC                                              Level 1
Industry_code_NZSIOC                                                       99999
Industry_name_NZSIOC                                              All industries
Units                                                         Dollars (millions)
Variable_code                                                                H01
Variable_name                                                       Total income
Variable_category                                          Financial performance
Value                                                                     979594
Industry_code_ANZSIC06         ANZSIC06 divisions A-S (excluding classes K633...
Name: 0, dtype: object

In [108]:
df = pd.read_csv('prices.csv')

In [115]:
df1 = df.dropna()
df1.head(5)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [124]:
data = {
    'Name': ['Ram', 'Shyam', 'Geeta', 'Mohan'],
    'Age': [25, None, 22, None],
    'City': ['Jaipur', 'Delhi', None, 'Mumbai']
}

df2 = pd.DataFrame(data)

In [132]:
newdf2 = df2.fillna(1)
newdf2

    Name   Age    City
0    Ram  25.0  Jaipur
1  Shyam   1.0   Delhi
2  Geeta  22.0       1
3  Mohan   1.0  Mumbai

In [136]:
newdf2 = df2.dropna()
newdf2

  Name   Age    City
0  Ram  25.0  Jaipur

In [145]:
cn = pd.read_csv('prices.csv')

In [146]:
cn.head(3)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...

In [149]:
rename_cn = cn.rename(columns = {"Year": "Yrs"})

rename_cn.head(3)

,Yrs,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...

In [155]:
units_1 = cn.rename(columns = {"Units": "Units_in_$"})
units_1.head(3)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units_in_$,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...

In [157]:
df = pd.read_csv('prices.csv')

In [159]:
df.head(3)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...

In [166]:
df['zeros'] = [0 for i in range(len(df))]

In [168]:
df.head(3)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06,zeros
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...,0
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...,0
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...,0